### ISSUE TITLE
Intoduce a simpler way to add neighbors to a selectable element

### ISSUE THREAD

**Issue by KonstantinSimeonov** [KonstantinSimeonov/GnomUi#1]
The current routine for adding neighbors is way too clunky, need tp discuss and realize a method for convinient neighbor addition

**Comment by borisbsv** [comment]
Implementing AddNeighbor method to the Node class and ISelectable interface.
If we're not too lazy, we'll add a planar distance calculation for neighbor selection as a UX improvement.

**Comment by KonstantinSimeonov** [comment]
we're too lazy
